# Generated by Django 5.0.7 on 2024-08-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='action',
            old_name='varb',
            new_name='verb',
        ),
    ]
